### PR TITLE
Sign in + Sign out Component 

### LINKED ISSUE #18: Sign in + Sign out Components Initial

### PR DESCRIPTION
**Pull request by oupadhyay**
It just uses the MUI components rather than the created `TextBox` and `Button` components because it was easier. :+1: 

This should be changed later on.

Closes #18 and replaces #19

### CODE REVIEW

**Comment by oupadhyay** [comment]
I am working on to make the components without the MUI Treasury and style them appropriately. We shall see how this works out.

**Comment by oupadhyay** [comment]
I have created a new repo with the new sign-in and sign-up components. They match better with the theme right now. However, I am not sure how to have a multistage form. @DheekshuKumar How does the wizard work?

[Github Link](https://github.com/oupadhyay/react-sign-in-up)

**Comment by DheekshuKumar** [comment]
Seems like there are a lot of extra fluff files that were added that might not be necessary? I think a good thing to do would be to schedule a meeting with @johancc to get a better idea how the backend is going to be implemented. You can take a look at how the Wizard works from the master branch. 

Just run App.js and it should be clear. 

I think you, johan, and maybe grab someone else interested in back-end work -- to discuss how to build the Registration Form. Focus on that for now maybe? And we can do the sign in component later.

**Comment by oupadhyay** [comment]
Lots of things will change and meetings must be had.

**Pull request closed without merging**
